dist: xenial
sudo: true
language: python
python:
- '3.6'
matrix:
  include:
    - python: 3.7
cache: pip
install:
- pip install -r requirements.txt
- pip install -U pytest pytest-cov codecov
- pip install black
script:
- pytest brainlight/ tests/
- black --check --diff ./brainlight ./tests
after_success:
- codecov

deploy:
- provider: pypi
  user: "bvarjavand"
  password:
    secure: xd
  on:
    tags: true
    repo: neurodata/brainlight
    python: '3.7'
