dist: xenial
sudo: true
language: python
python:
- '3.6'
matrix:
  include:
  - python: 3.7
cache: pip
before_install:
- ./.aws.sh
install:
- pip install -r requirements.txt
- pip install -U pytest pytest-cov codecov
- pip install black
script:
- pytest brainlit/ tests/
- black --check --diff ./brainlit ./tests
after_success:
- codecov
env:
  global:
  - secure: wtwyurwcZbUeIupwFiKDC964skZxWhRQyPZy761Ktr5RGsj8WYi31OmZXP5jGptncnx4dtDa0qbkoamxsE0u6rdINJwmcQal6Ga5YJ+mIkCj0YRlvM1kPy6bcmNGK1k3b6/nT3qfdatKKB9y4ab5TQ9OfF2Av95BEtHBH7K4qlg9H9Jn/Pvo60rFl20vOdDigHMc+wpYhOBTfOcPcgd+wPaJcYz3MXhRr1+0IpRQYlEZpN/ASnEHIcqMdmIYhcVe6Xbm4GU8gNWqZxKLZoZSm9z1rBJp6eUCilCY2VUeOBDZRB0q3wurptPGqNNi7aFrW6Oz9U6oToOhdVUk3pYfpHdH5F2R9SJ5JxV1adisOmJQ9ndeaZId17zcCDTk2sV4zAd+ZwBla34Vv9lrOrIBYpwQ8FehBqIC1K8ib7GqOJVEdIOIBA8hBIrnfv0u8RzxJ5esESGEO9JhpyfkWbUA6G05xRD61Qj99saqvIGv18aVSR3+ERvJHrP0V//JDHQ3+0VDlnEmR2I8kc4Ci1w0tV0rZqhUavxOSfPxy2A7Hslw0Eq9f/D5k/Mexq5BWuXN7UG1VWCtG34yTOfxJ9YgUGnZZ5w9t2U/euwyqSU/Q5QUITZP/XOsoUwUBoWZVZK9xr0CqbouTt2mJ4FnlWeGvh6hT9u2sQH/G4AtRTeqKLs=
  - secure: V6wihCZjlzPgatrhNoZi9RI6cNFmHQQKq0NZCpiB+yfZHO+O68YdZ5zgsI71hidCQhm4NrZE+/Hxv/0eQoRvEHQZ3spVHpeO+++ng8dhbWg3UjKVuHtm614mUCbpCaNQ8qIPHulEDqiqcR49E/FFVBLDprY90pNdJLzXEAFxS+XlIAB4Ki3zqMtsFcuAynwQ6uxGhY5y1WSdLBCT7kEkuvpmpyyZjk2kpTeLH1qYuWB4RWdoMS+soV9Gd+cKpbHubpBUY0/i1whipASdt2ElECupAJ6jeLevjdYffuJpSqj2esszWdjFqZPmO9hAg64g71c5GcYYPU4LfZa7s10dIPsQFJtq2nbwT8DBesSR09NGDw8FxtFORXVxXfu4T+/wA31Y5mqRSbz804x2bB9o9CTF4wIyS56oiJoK55qQiovFOHFK53IH+vzIr+ONJ8zsTg+dswlQq64MQ6RBtEtLYXV2TstxFcbmfdZSIXajDof0wYRMEpKMwztc7L2TZBxa6dih1r3u3+F4w8eM3mIEem4mOlpJiZJYJl0gWQcjhRSpyHsmHBYFGWXoIOa5M/BRee8Ys6wNMiylylpoEA7Mh4vZ+Q3d5rJj2hZRp8B+ELqxqRHqxXRP/sCatWJRNjH37+4ps/BZ8MMYta3ubHlmMS2sVKg1Sqtrgz/IP9+UX6I=
